version: '3.8'
services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    ports:
      - "3306:3306"

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
    ports:
      - "5432:5432"

  memcached:
    image: memcached:latest
    ports:
      - "11211:11211"
    environment:
      - MEMCACHED_MEMORY_LIMIT=64
      - MEMCACHED_MAX_CONNECTIONS=1024
