name: Test
permissions: write
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  phpunit:
    name: PHPUnit
    runs-on: ubuntu-20.04
    env:
      DB_DATABASE: test
      DB_USER: test
      DB_PASSWORD: test

    strategy:
      fail-fast: false
      matrix:
        php-version:
          - 8.1
          - 8.2

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          coverage: pcov
          ini-values: zend.assertions=1, assert.exception=1
          php-version: ${{ matrix.php-version }}
          extensions: memcached
          tools: cs2pr

      - name: Install dependencies with Composer
        uses: ramsey/composer-install@v2

      - name: Create and set permissions on SQLite Database
        run: |
          touch test.db
          sudo chown $USER:$USER test.db
          chmod 755 test.db

          # Verify SQLite installation and permissions
      - name: Verify SQLite setup
        run: |
          sqlite3 --version
          sqlite3 test.db "CREATE TABLE IF NOT EXISTS test (id INTEGER PRIMARY KEY, name TEXT);"
          ls -l test.db

      - name: Login to DockerHub
        run: echo ${{ secrets.docker_password }} | docker login -u ${{ secrets.docker_username }} --password-stdin

      - name: Build and Run Docker Compose
        run: |
            sudo docker-compose up -d --wait

      - name: Run PHPUnit
        run: |
          export $ENV
          vendor/bin/phpunit --coverage-clover=coverage.xml

      - name: Upload coverage file
        uses: actions/upload-artifact@v3
        with:
          name: phpunit-${{ matrix.deps }}-${{ matrix.php-version }}.coverage
          path: coverage.xml
  upload_coverage:
    name: Upload coverage to Codecov
    runs-on: ubuntu-20.04
    needs:
      - phpunit

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Download coverage files
        uses: actions/download-artifact@v3
        with:
          path: reports

      - name: Upload to Codecov
        uses: codecov/codecov-action@v3
        with:
          directory: reports
