name: Test

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  phpunit:
    name: PHPUnit
    runs-on: ubuntu-20.04
    env:
      DB_DATABASE: test
      DB_USER: test
      DB_PASSWORD: test

    strategy:
      fail-fast: false
      matrix:
        php-version:
          - 8.1
          - 8.2

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          coverage: pcov
          ini-values: zend.assertions=1, assert.exception=1
          php-version: ${{ matrix.php-version }}
          tools: cs2pr

      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup SQLite
        run: sudo apt-get install -y sqlite3

      - name: Set database permissions
        run: |
          touch test/test.db
          chmod 666 test/test.db

      - name: Login to DockerHub
        run: echo ${{ secrets.docker_password }} | docker login -u ${{ secrets.docker_username }} --password-stdin

      - name: Build and Run Docker Compose
        run: |
            sudo docker-compose up -d

      - name: Install dependencies with Composer
        uses: ramsey/composer-install@v2

      - name: Run PHPUnit
        run: |
          export $ENV
          vendor/bin/phpunit --coverage-clover=coverage.xml

      - name: Upload coverage file
        uses: actions/upload-artifact@v3
        with:
          name: phpunit-${{ matrix.deps }}-${{ matrix.php-version }}.coverage
          path: coverage.xml
